export const BIBLE_BOOKS = [
    { id: 'GEN', name: 'Génesis', chapters: 50, testament: 'Antiguo Testamento' },
    { id: 'EXO', name: 'Éxodo', chapters: 40, testament: 'Antiguo Testamento' },
    { id: 'LEV', name: 'Levítico', chapters: 27, testament: 'Antiguo Testamento' },
    { id: 'NUM', name: 'Números', chapters: 36, testament: 'Antiguo Testamento' },
    { id: 'DEU', name: 'Deuteronomio', chapters: 34, testament: 'Antiguo Testamento' },
    { id: 'JOS', name: 'Josué', chapters: 24, testament: 'Antiguo Testamento' },
    { id: 'JDG', name: 'Jueces', chapters: 21, testament: 'Antiguo Testamento' },
    { id: 'RUT', name: 'Rut', chapters: 4, testament: 'Antiguo Testamento' },
    { id: '1SA', name: '1 Samuel', chapters: 31, testament: 'Antiguo Testamento' },
    { id: '2SA', name: '2 Samuel', chapters: 24, testament: 'Antiguo Testamento' },
    { id: '1KI', name: '1 Reyes', chapters: 22, testament: 'Antiguo Testamento' },
    { id: '2KI', name: '2 Reyes', chapters: 25, testament: 'Antiguo Testamento' },
    { id: '1CH', name: '1 Crónicas', chapters: 29, testament: 'Antiguo Testamento' },
    { id: '2CH', name: '2 Crónicas', chapters: 36, testament: 'Antiguo Testamento' },
    { id: 'EZR', name: 'Esdras', chapters: 10, testament: 'Antiguo Testamento' },
    { id: 'NEH', name: 'Nehemías', chapters: 13, testament: 'Antiguo Testamento' },
    { id: 'TOB', name: 'Tobías', chapters: 14, testament: 'Antiguo Testamento' },
    { id: 'JDT', name: 'Judit', chapters: 16, testament: 'Antiguo Testamento' },
    { id: 'EST', name: 'Ester', chapters: 10, testament: 'Antiguo Testamento' },
    { id: '1MA', name: '1 Macabeos', chapters: 16, testament: 'Antiguo Testamento' },
    { id: '2MA', name: '2 Macabeos', chapters: 15, testament: 'Antiguo Testamento' },
    { id: 'JOB', name: 'Job', chapters: 42, testament: 'Antiguo Testamento' },
    { id: 'PSA', name: 'Salmos', chapters: 150, testament: 'Antiguo Testamento' },
    { id: 'PRO', name: 'Proverbios', chapters: 31, testament: 'Antiguo Testamento' },
    { id: 'ECC', name: 'Eclesiastés', chapters: 12, testament: 'Antiguo Testamento' },
    { id: 'SNG', name: 'Cantares', chapters: 8, testament: 'Antiguo Testamento' },
    { id: 'WIS', name: 'Sabiduría', chapters: 19, testament: 'Antiguo Testamento' },
    { id: 'SIR', name: 'Eclesiástico', chapters: 51, testament: 'Antiguo Testamento' },
    { id: 'ISA', name: 'Isaías', chapters: 66, testament: 'Antiguo Testamento' },
    { id: 'JER', name: 'Jeremías', chapters: 52, testament: 'Antiguo Testamento' },
    { id: 'LAM', name: 'Lamentaciones', chapters: 5, testament: 'Antiguo Testamento' },
    { id: 'BAR', name: 'Baruc', chapters: 6, testament: 'Antiguo Testamento' },
    { id: 'EZK', name: 'Ezequiel', chapters: 48, testament: 'Antiguo Testamento' },
    { id: 'DAN', name: 'Daniel', chapters: 14, testament: 'Antiguo Testamento' },
    { id: 'HOS', name: 'Oseas', chapters: 14, testament: 'Antiguo Testamento' },
    { id: 'JOL', name: 'Joel', chapters: 4, testament: 'Antiguo Testamento' },
    { id: 'AMO', name: 'Amós', chapters: 9, testament: 'Antiguo Testamento' },
    { id: 'OBA', name: 'Abdías', chapters: 1, testament: 'Antiguo Testamento' },
    { id: 'JON', name: 'Jonás', chapters: 4, testament: 'Antiguo Testamento' },
    { id: 'MIC', name: 'Miqueas', chapters: 7, testament: 'Antiguo Testamento' },
    { id: 'NAM', name: 'Nahúm', chapters: 3, testament: 'Antiguo Testamento' },
    { id: 'HAB', name: 'Habacuc', chapters: 3, testament: 'Antiguo Testamento' },
    { id: 'ZEP', name: 'Sofonías', chapters: 3, testament: 'Antiguo Testamento' },
    { id: 'HAG', name: 'Hageo', chapters: 2, testament: 'Antiguo Testamento' },
    { id: 'ZEC', name: 'Zacarías', chapters: 14, testament: 'Antiguo Testamento' },
    { id: 'MAL', name: 'Malaquías', chapters: 3, testament: 'Antiguo Testamento' },
    { id: 'MAT', name: 'Mateo', chapters: 28, testament: 'Nuevo Testamento' },
    { id: 'MRK', name: 'Marcos', chapters: 16, testament: 'Nuevo Testamento' },
    { id: 'LUK', name: 'Lucas', chapters: 24, testament: 'Nuevo Testamento' },
    { id: 'JHN', name: 'Juan', chapters: 21, testament: 'Nuevo Testamento' },
    { id: 'ACT', name: 'Hechos', chapters: 28, testament: 'Nuevo Testamento' },
    { id: 'ROM', name: 'Romanos', chapters: 16, testament: 'Nuevo Testamento' },
    { id: '1CO', name: '1 Corintios', chapters: 16, testament: 'Nuevo Testamento' },
    { id: '2CO', name: '2 Corintios', chapters: 13, testament: 'Nuevo Testamento' },
    { id: 'GAL', name: 'Gálatas', chapters: 6, testament: 'Nuevo Testamento' },
    { id: 'EPH', name: 'Efesios', chapters: 6, testament: 'Nuevo Testamento' },
    { id: 'PHP', name: 'Filipenses', chapters: 4, testament: 'Nuevo Testamento' },
    { id: 'COL', name: 'Colosenses', chapters: 4, testament: 'Nuevo Testamento' },
    { id: '1TH', name: '1 Tesalonicenses', chapters: 5, testament: 'Nuevo Testamento' },
    { id: '2TH', name: '2 Tesalonicenses', chapters: 3, testament: 'Nuevo Testamento' },
    { id: '1TI', name: '1 Timoteo', chapters: 6, testament: 'Nuevo Testamento' },
    { id: '2TI', name: '2 Timoteo', chapters: 4, testament: 'Nuevo Testamento' },
    { id: 'TIT', name: 'Tito', chapters: 3, testament: 'Nuevo Testamento' },
    { id: 'PHM', name: 'Filemón', chapters: 1, testament: 'Nuevo Testamento' },
    { id: 'HEB', name: 'Hebreos', chapters: 13, testament: 'Nuevo Testamento' },
    { id: 'JAS', name: 'Santiago', chapters: 5, testament: 'Nuevo Testamento' },
    { id: '1PE', name: '1 Pedro', chapters: 5, testament: 'Nuevo Testamento' },
    { id: '2PE', name: '2 Pedro', chapters: 3, testament: 'Nuevo Testamento' },
    { id: '1JN', name: '1 Juan', chapters: 5, testament: 'Nuevo Testamento' },
    { id: '2JN', name: '2 Juan', chapters: 1, testament: 'Nuevo Testamento' },
    { id: '3JN', name: '3 Juan', chapters: 1, testament: 'Nuevo Testamento' },
    { id: 'JUD', name: 'Judas', chapters: 1, testament: 'Nuevo Testamento' },
    { id: 'REV', name: 'Apocalipsis', chapters: 22, testament: 'Nuevo Testamento' }
];
